### ISSUE TITLE
archived on CRAN

### ISSUE THREAD

**Issue by sckott** [kehraProject/r_rdefra#10]
https://cran.rstudio.com/web/packages/rdefra/ hey @cvitolo it's been archived on CRAN. can we help get it updated?

**Comment by cvitolo** [comment]
Hi @sckott , thanks for reaching out. I have just re-submitted. Fingers crossed all runs fine :)

**Comment by sckott** [comment]
great, thx!

**Comment by cvitolo** [comment]
Closing this issue as the package is back on CRAN now.
