### ISSUE TITLE
pkgdown build failure in rdefra_vignette.Rmd

### ISSUE THREAD

**Issue by jeroen** [kehraProject/r_rdefra#11]
See https://dev.ropensci.org/job/rdefra/lastBuild/console

```
── Building articles ───────────────────────────────────────────────────────────
Writing 'articles/index.html'
Reading 'vignettes/rdefra_vignette.Rmd'
Error : callr subprocess failed: invalid multibyte string at '<a0>\<c8><c9>'
Error: callr subprocess failed: callr subprocess failed: invalid multibyte string at '<a0>\<c8><c9>'
Execution halted
```

**Comment by cvitolo** [comment]
Hi @jeroen I tried to fix this but I'm struggling to understand what the problem is.
I thought it was due to non-ASCII characters in the "stations" dataset...but it's clearly not.

**Comment by jeroen** [comment]
Hmm 🤔 does your package pull in text or data that may contain non-ascii characters?

**Comment by cvitolo** [comment]
Yes, the package scrapes a website therefore it could pull in non-ASCII characters. The function ukair_catalogue() contains steps to retrieve the raw data and clean it up. However, as far as I understand, the failure happens as soon as the raw data is pulled in (before the clean up step). 

I also do not understand why it fails [here](https://dev.ropensci.org/job/rdefra/lastBuild/console) and not in [travis](https://travis-ci.org/ropensci/rdefra/builds)

**Comment by cvitolo** [comment]
It seems to be working now. It was probably an issue on the server side.
