### ISSUE TITLE
Vignette failure

### ISSUE THREAD

**Issue by maelle** [kehraProject/r_rdefra#14]
:wave: @cvitolo!

We see a vignette failure https://github.com/r-universe/ropensci/runs/5447146461?check_suite_focus=true

Locally I can build the vignette, and I re-launched the workflow above but the timeout appeared again.

If the web service rdefra is wrapping is known to be slow/not always working, maybe you could pre-compute the vignette? https://ropensci.org/blog/2019/12/08/precompute-vignettes/

**Comment by cvitolo** [comment]
Hi @maelle , thanks for spotting this.

This is now fixed by recompiling the vignette, as you suggested.
