### ISSUE TITLE
dependency on rgdal

### ISSUE THREAD

**Issue by maelle** [kehraProject/r_rdefra#17]
:wave: @cvitolo! this package uses rgdal that has been retired from CRAN.

Are you still able to maintain rdefra? I have a vague memory of our trying to find new maintainers?

**Comment by cvitolo** [comment]
Hi @maelle!

I thought @cherylisabella took over the package, as documented here
https://github.com/ropensci/rdefra/issues/15.

Please let me know, if this is not the case.

**Comment by maelle** [comment]
oh right, sorry! @cherylisabella do you still maintain this package?

**Comment by maelle** [comment]
I will archive this package as there's currently no maintainer, and it depends on retired packages. We could still unarchive it on request.

**Comment by cvitolo** [comment]
Hello @maelle, please see contribution [here](https://github.com/ropensci/rdefra/pull/19) to fix #17.

**Comment by maelle** [comment]
Yep sorry I saw that later.
