### ISSUE TITLE
New maintainer wanted :-)

### ISSUE THREAD

**Issue by maelle** [kehraProject/r_rdefra#18]
Note #17

**Comment by maelle** [comment]
I will archive this package as there's currently no maintainer, and it depends on retired packages. We could still unarchive it on request.

**Comment by steffilazerte** [comment]
Hi @olivroy, are you the current maintainer of this package?

**Comment by olivroy** [comment]
Hi! Not really.. I got rid of the deprecated spatial packages (rgdal, maptools) but I wasn't able to reconcile the API to extract the correct data. I think it is safe to archive the package at this point
