### ISSUE TITLE
Merge README_files folder to assets?

### ISSUE THREAD

**Issue by haozhu233** [kehraProject/r_rdefra#3]
Hi, @cvitolo, 
The `README_files` folder and the `assets` folder seem to be the same thing. Maybe you want to merge them? ;)

**Comment by cvitolo** [comment]
Hi @haozhu233, I did not merge them because the README_files folder contains figure generated by the Rmd while assets/figures contains screenshots I have created and that I use for the README as well as the vignettes. Is this considered bad practice?

**Comment by haozhu233** [comment]
Haha, I won't consider that as a bad practice at all and your explanation makes sense. I just sort of feel like these hosted images don't "deserve" two main folders in the root directories. If you don't feel in the same way, feel free to ignore that~ 😋
