### ISSUE TITLE
Install instructions for dev version

### ISSUE THREAD

**Issue by grahamrp** [kehraProject/r_rdefra#4]
The install instructions for the development version don't work for me:

`devtools::install_github('cvitolo/rdefra')`

> Downloading GitHub repo cvitolo/rdefra@master
> from URL https://api.github.com/repos/cvitolo/rdefra/zipball/master
> Error in stop(github_error(request)) : Not Found (404)

Should README.md refer to ropenscilabs repository instead? This _does_ work for me:

`devtools::install_github('ropenscilabs/rdefra')`

**Comment by cvitolo** [comment]
You are right, I forgot to update the repo location after migrating the package to ropenscilabs. Fixed now, thanks a lot!
