### ISSUE TITLE
Wrong permissions? I see ALL the ropenscilabs repositories in my travis!

### ISSUE THREAD

**Issue by cvitolo** [kehraProject/r_rdefra#5]
@sckott somebody must have given me some sort of permission on ropenscilabs, I see ALL the ropenscilabs repositories in my travis dashboard. Would you be able to fix this? Many thanks!

**Comment by sckott** [comment]
can you include a screenshot of what you see?

**Comment by cvitolo** [comment]
@sckott here it is (on the left hand side I can see all the repos in ropenscilabs):

![screenshot from 2017-01-16 21 42 35](https://cloud.githubusercontent.com/assets/4742575/22000007/e498d36a-dc34-11e6-9c48-6d5841f0a031.png)

In addition to that, I do not have admin right on my own repo (rdefra), see in the screenshot below I do not have access to the repo settings

![screenshot from 2017-01-16 21 45 42](https://cloud.githubusercontent.com/assets/4742575/22000117/642f5dc4-dc35-11e6-8750-7a76eb0eb4e1.png)

**Comment by sckott** [comment]
sent you an invite to ropensci slack - we can quickly chat about whatever in there 

for this, i think it's b/c you have admin access on `hddtools`

for rderfra you have `Write` access, do you need Admin?

**Comment by cvitolo** [comment]
@sckott Thanks for the invite to slack. 

I got admin access on hddtools literally few hours ago but the problem with travis has been there for ages.

Could you please give me admin access on rdefra? I'd like to set up a website for this package.
Many thanks!

**Comment by sckott** [comment]
okay, try it again

**Comment by cvitolo** [comment]
@sckott I can see the settings for rdefra repo now, many thanks!

Any idea how to sort the travis problem?

**Comment by sckott** [comment]
can you do a screen share tomorrow? if so what time is good for you?

**Comment by cvitolo** [comment]
Sure, what about 8pm UK time?

Thanks

On 16 Jan 2017 23:13, "Scott Chamberlain" <notifications@github.com> wrote:

can you do a screen share tomorrow? if so what time is good for you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ropenscilabs/rdefra/issues/5#issuecomment-272982981>,
or mute the thread

**Comment by sckott** [comment]
so it's about 340 pm right now for you?  so  8 pm will be 12 pm my time. sounds good

**Comment by cvitolo** [comment]
Perfect! Talk to you soon!
