### ISSUE TITLE
PROJ 6 failures in rdefra

### ISSUE THREAD

**Issue by rsbivand** [kehraProject/r_rdefra#9]
I'm testing rgdal and its reverse dependencies with PROJ 6 and -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H. The CRS offered by PROJ >= 6 are changing, so that even though rgdal is still using the proj_api.h interface (for a few more months), the underlying CRS parameters are changing. Since few are using PROJ 6 yet, you have some time to fix this as rgdal will be built with < PROJ 6 metadata files in most cases. However, PROJ 6 was released 1 March, so you'll need to adapt. I attach my check files:

[testthat.Rout.zip](https://github.com/ropensci/rdefra/files/2951413/testthat.Rout.zip)
[00check.log](https://github.com/ropensci/rdefra/files/2951415/00check.log)

**Comment by rsbivand** [comment]
Issue still present in PROJ 6.1.0

**Comment by cvitolo** [comment]
Hi @rsbivand! Thanks for reporting this. I have updated the tests to be compatible with changes introduced by PROJ6.
